# Generated by Django 2.2.6 on 2019-10-30 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Category', verbose_name='Категорія'),
        ),
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(default='', max_length=50, verbose_name='Ключові слова'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default='', verbose_name='Текст новини'),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_min',
            field=models.TextField(default='', max_length=200, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=70, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
