# Generated by Django 2.2.6 on 2019-10-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField()),
                ('char_field', models.CharField(max_length=5)),
                ('float_field', models.FloatField()),
                ('date_field', models.DateField(auto_now=True)),
                ('date_time_field', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=20)),
            ],
        ),
    ]
